name: Chatterbox Services Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: docker-compose build
    
    - name: Start services
      run: |
        docker-compose up -d
        echo "Waiting 60 seconds for services to fully start..."
        sleep 60
    
    - name: Check container status
      run: |
        docker ps -a
        docker logs chatterbox-tts --tail=50
    
    - name: Run tests
      run: pytest tests/test_services.py -v --tb=short
    
    - name: Show logs on failure
      if: failure()
      run: |
        echo "=== Container Logs ==="
        docker logs chatterbox-tts
        echo "=== Container Status ==="
        docker ps -a
        echo "=== Container Processes ==="
        docker exec chatterbox-tts ps aux || true
    
    - name: Cleanup
      if: always()
      run: docker-compose down
